CREATE SCHEMA `db_dev_desktop_20182` ;

CREATE TABLE `db_dev_desktop_20182`.`PRODUTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `valor` DOUBLE NULL,
  `peso` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));
  
  CREATE TABLE `db_dev_desktop_20182`.`FUNCIONARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `MATRICULA` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`));


  